//! `ui.*` — natives for building Flint UI's default styled HTML, one
//! `(html: str, ...) -> str` fragment at a time. Each native appends a piece
//! of markup (and, for `ui.window`, the document shell and default
//! stylesheet) to an accumulator string, mirroring `string.concat`. See
//! `crates/flint/src/stdlib/mod.rs` for the one-file-per-native layout.

mod accordion;
mod accordion_end;
mod accordion_item;
mod accordion_item_end;
mod action_bar;
mod action_bar_end;
mod alert;
mod badge;
mod breadcrumb;
mod breadcrumb_end;
mod breadcrumb_item;
mod button;
mod caption;
mod card;
mod card_end;
mod checkbox;
mod code;
mod column;
mod column_end;
mod dialog;
mod dialog_alert;
mod dialog_confirm;
mod dialog_end;
mod dialog_prompt;
mod dialog_trigger;
mod divider;
mod empty;
mod field;
mod fieldset;
mod fieldset_end;
mod file;
mod footer;
mod footer_end;
mod form;
mod form_end;
mod hidden;
mod image;
mod input;
mod kbd;
mod layout;
mod layout_end;
mod layout_main;
mod layout_main_end;
mod link;
mod list;
mod list_end;
mod list_item;
mod menu;
mod menu_active;
mod menu_end;
mod menu_item;
mod meter;
mod nav_item;
mod navbar;
mod navbar_end;
mod number;
mod ol;
mod ol_end;
mod ol_item;
mod option;
mod page_current;
mod page_item;
mod pagination;
mod pagination_end;
mod password;
mod progress;
mod radio;
mod row;
mod row_end;
mod section;
mod section_end;
mod select;
mod select_end;
mod sidebar;
mod sidebar_end;
mod stat;
mod status;
mod step;
mod steps;
mod steps_end;
mod submit;
mod support;
pub use support::{UI_CSS, UI_JS};
mod tab;
mod tab_panel;
mod tab_panel_end;
mod table;
mod table_end;
mod tabs;
mod tabs_body;
mod tabs_end;
mod td;
mod text;
mod textarea;
mod tfoot;
mod tfoot_end;
mod th;
mod title;
mod toolbar;
mod toolbar_end;
mod tr;
mod tr_end;
mod tree;
mod tree_end;
mod tree_group;
mod tree_group_end;
mod tree_item;
mod window;
mod window_end;

use crate::vm::NativeRegistry;

pub fn register(registry: &mut NativeRegistry) {
    registry.register_exact("ui.window", 2, window::make());
    registry.register_exact("ui.window_end", 1, window_end::make());
    registry.register_exact("ui.navbar", 1, navbar::make());
    registry.register_exact("ui.navbar_end", 1, navbar_end::make());
    registry.register_exact("ui.nav_item", 3, nav_item::make());
    registry.register_exact("ui.breadcrumb", 1, breadcrumb::make());
    registry.register_exact("ui.breadcrumb_item", 3, breadcrumb_item::make());
    registry.register_exact("ui.breadcrumb_end", 1, breadcrumb_end::make());
    registry.register_exact("ui.card", 2, card::make());
    registry.register_exact("ui.card_end", 1, card_end::make());
    registry.register("ui.section", section::make());
    registry.register_exact("ui.section_end", 1, section_end::make());
    registry.register_exact("ui.tabs", 1, tabs::make());
    registry.register_exact("ui.tab", 3, tab::make());
    registry.register_exact("ui.tabs_body", 1, tabs_body::make());
    registry.register_exact("ui.tab_panel", 2, tab_panel::make());
    registry.register_exact("ui.tab_panel_end", 1, tab_panel_end::make());
    registry.register_exact("ui.tabs_end", 1, tabs_end::make());
    registry.register_exact("ui.row", 1, row::make());
    registry.register_exact("ui.row_end", 1, row_end::make());
    registry.register_exact("ui.column", 1, column::make());
    registry.register_exact("ui.column_end", 1, column_end::make());
    registry.register_exact("ui.title", 2, title::make());
    registry.register_exact("ui.text", 2, text::make());
    registry.register_exact("ui.field", 3, field::make());
    registry.register_exact("ui.badge", 2, badge::make());
    registry.register_exact("ui.alert", 3, alert::make());
    registry.register_exact("ui.status", 3, status::make());
    registry.register_exact("ui.divider", 1, divider::make());
    registry.register_exact("ui.progress", 3, progress::make());
    registry.register_exact("ui.code", 2, code::make());
    registry.register_exact("ui.link", 3, link::make());
    registry.register_exact("ui.table", 1, table::make());
    registry.register_exact("ui.table_end", 1, table_end::make());
    registry.register_exact("ui.tr", 1, tr::make());
    registry.register_exact("ui.tr_end", 1, tr_end::make());
    registry.register_exact("ui.th", 2, th::make());
    registry.register_exact("ui.td", 2, td::make());
    registry.register_exact("ui.button", 3, button::make());
    registry.register_exact("ui.form", 3, form::make());
    registry.register_exact("ui.form_end", 1, form_end::make());
    registry.register_exact("ui.input", 3, input::make());
    registry.register_exact("ui.textarea", 3, textarea::make());
    registry.register_exact("ui.select", 3, select::make());
    registry.register_exact("ui.select_end", 1, select_end::make());
    registry.register_exact("ui.option", 3, option::make());
    registry.register_exact("ui.checkbox", 4, checkbox::make());
    registry.register_exact("ui.radio", 4, radio::make());
    registry.register_exact("ui.hidden", 3, hidden::make());
    registry.register_exact("ui.submit", 2, submit::make());
    registry.register_exact("ui.fieldset", 2, fieldset::make());
    registry.register_exact("ui.fieldset_end", 1, fieldset_end::make());
    registry.register_exact("ui.pagination", 1, pagination::make());
    registry.register_exact("ui.page_item", 3, page_item::make());
    registry.register_exact("ui.page_current", 2, page_current::make());
    registry.register_exact("ui.pagination_end", 1, pagination_end::make());
    registry.register_exact("ui.toolbar", 1, toolbar::make());
    registry.register_exact("ui.toolbar_end", 1, toolbar_end::make());
    registry.register_exact("ui.list", 1, list::make());
    registry.register_exact("ui.list_item", 2, list_item::make());
    registry.register_exact("ui.list_end", 1, list_end::make());
    registry.register_exact("ui.stat", 3, stat::make());
    registry.register_exact("ui.image", 3, image::make());
    registry.register_exact("ui.password", 3, password::make());
    registry.register_exact("ui.file", 3, file::make());
    registry.register_exact("ui.number", 3, number::make());
    registry.register_exact("ui.action_bar", 1, action_bar::make());
    registry.register_exact("ui.action_bar_end", 1, action_bar_end::make());
    registry.register_exact("ui.empty", 2, empty::make());
    registry.register_exact("ui.tree", 1, tree::make());
    registry.register_exact("ui.tree_item", 3, tree_item::make());
    registry.register_exact("ui.tree_group", 2, tree_group::make());
    registry.register_exact("ui.tree_group_end", 1, tree_group_end::make());
    registry.register_exact("ui.tree_end", 1, tree_end::make());
    registry.register_exact("ui.steps", 1, steps::make());
    registry.register_exact("ui.step", 3, step::make());
    registry.register_exact("ui.steps_end", 1, steps_end::make());
    registry.register("ui.footer", footer::make());
    registry.register_exact("ui.footer_end", 1, footer_end::make());
    registry.register_exact("ui.dialog", 3, dialog::make());
    registry.register_exact("ui.dialog_end", 1, dialog_end::make());
    registry.register_exact("ui.dialog_trigger", 3, dialog_trigger::make());
    registry.register_exact("ui.dialog_alert", 4, dialog_alert::make());
    registry.register_exact("ui.dialog_confirm", 5, dialog_confirm::make());
    registry.register_exact("ui.dialog_prompt", 6, dialog_prompt::make());
    registry.register_exact("ui.layout", 1, layout::make());
    registry.register_exact("ui.layout_end", 1, layout_end::make());
    registry.register_exact("ui.sidebar", 1, sidebar::make());
    registry.register_exact("ui.sidebar_end", 1, sidebar_end::make());
    registry.register_exact("ui.main", 1, layout_main::make());
    registry.register_exact("ui.main_end", 1, layout_main_end::make());
    registry.register_exact("ui.menu", 2, menu::make());
    registry.register_exact("ui.menu_item", 3, menu_item::make());
    registry.register_exact("ui.menu_active", 3, menu_active::make());
    registry.register_exact("ui.menu_end", 1, menu_end::make());
    registry.register_exact("ui.accordion", 1, accordion::make());
    registry.register_exact("ui.accordion_item", 2, accordion_item::make());
    registry.register_exact("ui.accordion_item_end", 1, accordion_item_end::make());
    registry.register_exact("ui.accordion_end", 1, accordion_end::make());
    registry.register_exact("ui.ol", 1, ol::make());
    registry.register_exact("ui.ol_item", 2, ol_item::make());
    registry.register_exact("ui.ol_end", 1, ol_end::make());
    registry.register_exact("ui.kbd", 2, kbd::make());
    registry.register_exact("ui.caption", 2, caption::make());
    registry.register_exact("ui.tfoot", 1, tfoot::make());
    registry.register_exact("ui.tfoot_end", 1, tfoot_end::make());
    registry.register_exact("ui.meter", 3, meter::make());
}
