name: VSCode Extension Release

on:
  push:
    tags:
      - "vscode-v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Publish
        working-directory: extensions/vscode
        run: pnpm dlx @vscode/vsce publish --pat "${{ secrets.VSCE_PAT }}"
